output_dir: {{BIOPATHNET}}/experiments/single_SKG/relatives_complex/1000/10/10/grandParentOf/0/

dataset:
  class: biomedical
  path: {{BIOPATHNET}}/data/single_SKG/relatives_complex/1000/10/10/grandParentOf/0/
  include_factgraph: yes
  files: ['brg.txt', 'graph_learning.txt', 'graph_validation.txt', 'graph_test.txt']

task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    symmetric: no
  criterion: bce
  num_negative: 32
  strict_negative: no
  adversarial_temperature: 0.5
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  # neg_samp_strategy: sans # [sans, degree, inv_degree]
  # sans_rw_hops: "1000:2" # default 1000:2 # k=2 hop neighborhood approximated with 1000 random walks 
  full_batch_eval: no

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32
  
train:
  num_epoch: 5
  
metric: mrr
